---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-kv-app
  namespace: vault-app
spec:
  vaultAuthRef: vault-auth # VaultAuth name
  mount: secrets # Vault path mount
  type: kv-v2 # Vault type
  path: preprod # Vault path to synchronize
  refreshAfter: 5s # Delay before refresh
  destination:
    create: true
    name: vault-secrets-operator-kubernetes # kubernetes secret name
  # deployments to restart when secrets are updated
#  rolloutRestartTargets:
#    - kind: Deployment
#      name: my-app
