---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-secret-store-kubernetes
  namespace: vault-app
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "secrets"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "k3s"
          role: "demo"
          serviceAccountRef:
            name: vault-account
          secretRef:
            name: vault-auth-service-account-token
            key: token
