server:
  server:
    logLevel: debug
    dev:
      enabled: true # must be disabled in production
  standalone:
    enabled: true
    config: |
      ui = true
      cluster_name = "vault-standalone"
      listener "tcp" {
        tls_disable = 1
        address = "[::]:8200"
        cluster_address = "[::]:8201"
      }
      storage "file" {
        path = "/vault/data"
      }

  service:
    enabled: true

  dataStorage:
    enabled: true
    size: 10Gi
    storageClass: null
    accessMode: ReadWriteOnce

  ingress:
    enabled: true
    hosts:
      - host: vault.k3s.localhost

injector:
  enabled: false

ui:
  enabled: true
  serviceType: LoadBalancer
