---
apiVersion: v1
kind: Service
metadata:
  name: proxy-vault
  namespace: vault-app
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      name: http

---
apiVersion: v1
kind: Endpoints
metadata:
  name: proxy-vault # Must be equal to Service name for automatic mapping
  namespace: vault-app
subsets:
  - addresses:
      - ip: 192.168.1.1 # IP address of your external vault that you would like to proxy requests to
    ports:
      - port: 8200

#---
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  annotations:
#    nginx.ingress.kubernetes.io/rewrite-target: /
#  name: proxy-vault-ingress
#  namespace: vault-app
#spec:
#  ingressClassName: nginx
#  rules:
#    - host: proxy-vault.k3s.localhost
#      http:
#        paths:
#          - backend:
#              service:
#                name: proxy-vault # Here you specify the name of the Service traffic must be routed to
#                port:
#                  number: 80
#            path: /
#            pathType: ImplementationSpecific
