---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-external-secret
  namespace: vault-app
spec:
  refreshInterval: "5s"
  secretStoreRef:
    name: vault-secret-store
    kind: SecretStore
  target:
    name: vault-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: preprod
