---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-operator-account
  namespace: vault-app
secrets:
  - name: vault-operator-service-account-token

---
apiVersion: v1
kind: Secret
metadata:
  name: vault-operator-service-account-token
  namespace: vault-app
  annotations:
    kubernetes.io/service-account.name: vault-operator-account
type: kubernetes.io/service-account-token

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vault-operator-auth-delegator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: vault-operator-account
    namespace: vault-app
